### ISSUE TITLE
Simpler approach that eliminates R igraph dependency

### ISSUE THREAD

**Issue by jayhesselberth** [TomKellyGenetics/leiden#1]
Thanks for developing this approach to use the leidenalg with R.

Here is an approach that eliminates the dependency on the R igraph package, which is a heavy dependency, and also eliminates the need for an intermediary temp file.

I think you can replace: 

https://github.com/TomKellyGenetics/leiden/blob/b01bcd04ea6e2f2360723312244153f79020a053/R/leiden.R#L21-L26

with:

``` r
adj_mat <- as.matrix(ceiling(adj_mat))

## convert to python numpy.ndarray, then a list
adj_mat_py <- reticulate::r_to_py(adj_mat)
adj_mat_py <- adj_mat_py$tolist()

snn_graph <- ig$Graph$Adjacency(adj_mat_py)
```

Can you confirm?

**Comment by TomKellyGenetics** [comment]
Thanks for suggesting this. Have you tested this approach? Ideally, I would prefer that the function avoids writing to disk and passes the data directly to Python. Writing to disk is not permitted by CRAN so it would be great if we can avoid this.

**Comment by TomKellyGenetics** [comment]
This was a great suggestion at the time as igraph was not necessary as a dependency in R. However, it will be required to implement a method for calling on R igraph objects. This approach will avoid casting graph objects to adjacency matrices. For this reason igraph will be added as a dependency in version 0.3.0. See discussions here for details on why this is needed: https://github.com/satijalab/seurat/issues/1645
