### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by Jayesh-Kumar-Sundaram** [TomKellyGenetics/leiden#15]
Few months (Late may) back I installed Leiden R package and performed clustering on my data with the seed parameter as '123'. Yesterday I installed Leiden R package in my new system and tried to reproduce the results with the same data and also with the seed parameter as '123' (basically using the same old script as is). I am getting a different result compared to last time. I am not sure which version of the package I used few months back - I tried to reproduce my old results using the last three versions of Leiden R package (0.3.9, 0.3.8 and 0.3.7). Although the results are matching among different versions but they don't match my old results. Is there any other dependent package of Leiden I should worry about with respect to version control? Any ideas to reproduce my old results?

**Comment by TomKellyGenetics** [comment]
Hi @Jayesh-Kumar-Sundaram, sorry for the belated response. No changes to my knowledge have been made to this parameter in recent releases.

However, note that this package functions by calling the “leidenalg” module in Python. If this has been updated, it is possible that the seed parameter passed to it may have different results. I suggest checking the release notes here:
https://github.com/vtraag/leidenalg

You can also control the version of the Python module by running R in a coda environment (default name “r-reticulate” is recommended).

Note that in a future release (dev/0.4.0), I will migrate to calling the igraph version discussed in #1 which may lead to different results as well.

**Comment by TomKellyGenetics** [comment]
Note that there have not been major updates to the package functionality since version 0.3.6 in December 2020. Unless you were using an older version before then I wouldn’t expect any changes.

See here for details:
https://github.com/TomKellyGenetics/leiden/blob/master/NEWS.md
