### ISSUE TITLE
How to set the resolution_parameter?

### ISSUE THREAD

**Issue by Jon-bioinfo** [TomKellyGenetics/leiden#2]
The leidenalg find_partition function is: 
`def find_partition(graph, partition_type, initial_membership=None, weights=None, n_iterations=2, seed=None, **kwargs):`

with the description
`**kwargs are passed on to the constructor of the partition_type, including for example a resolution_parameter`

It seems like something to do with reticulate:::py_resolve_dots, but I can't figure it out.

I've tried things like:
```r
> membership <- leiden(adjacency_matrix, resolution_parameter=0.5)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() got an unexpected keyword argument 'resolution_parameter'
```

```r
> membership <- leiden(adjacency_matrix, c(resolution_parameter=0.5))
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'float' object is not iterable
```

```r
> membership <- leiden(adjacency_matrix, list(resolution_parameter=0.5))
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: membership list has invalid length
````

**Comment by TomKellyGenetics** [comment]
This can now be run with

```
leiden(adj_mat, partition_type = "RBConfigurationVertexPartition", resolution = 0.95)
```

Note that a `partition_type` which takes a `resolution_parameter` must be selected. See the Leiden python module documentation for more details: https://leidenalg.readthedocs.io/en/latest/reference.html

**Comment by TomKellyGenetics** [comment]
Passing any arguments in the leidenalg python functions is enabled with default `resolution = 1` (numeric/float) and others as `NULL` in R and `None` in Python. Other arguments have not been tested but should be supported.
