### ISSUE TITLE
resolution parameter and number of iteration in leiden R package

### ISSUE THREAD

**Issue by EEmanetci** [TomKellyGenetics/leiden#29]
hi, 

I am using leiden algorithm and I wonder how can be decide the best resolution parameter and number of iterations? Is "n_iteration" parameter in leiden function performes the iteration or shouldr we run the code multiple times? 

tank you,

Elif.

**Comment by TomKellyGenetics** [comment]
These parameters are described in the python documentation which the R package passes inputs to.
https://leidenalg.readthedocs.io/en/stable/intro.html
