### ISSUE TITLE
Pathological "\n" characters in man/leiden.Rd?

### ISSUE THREAD

**Issue by zaczap** [TomKellyGenetics/leiden#4]
I kept running into failed installations with:

    devtools::install_github("TomKellyGenetics/leiden")

Which would crash out w/ the following error message:

```
* installing *source* package ‘leiden’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) /private/var/folders/3w/9cctnv1n61q330djgstsfl7c00019l/T/RtmpbTeXmo/R.INSTALL14881221553c2/leiden/man/leiden.Rd:37: unknown macro '\n'
ERROR: installing Rd objects failed for package ‘leiden’
```

I forked and removed two "\n" in `man/leiden.Rd` and was then able to install from my forked repo successfully--I'm not sure if this issue is affecting anyone else?

**Comment by TomKellyGenetics** [comment]
Thanks for letting me know, I'll look into it. What OS are you using? Line endings  an be different.

Any reason why you are installing the github version from the master branch? It is available on CRAN and can be installed with: `install.packages("leiden")`

I've checked that this works with Mac OS.

**Comment by TomKellyGenetics** [comment]
I've resolved this in the development version.

```
library("devtools")
install_github("TomKellyGenetics/leiden", ref = "dev")
```

This will be released when the dependencies are available.

The latest version requires reticulate version 1.15 or higher.  Installing these may require one of these solutions.
 
```
install.packages("reticulate", type = "source")
```
```
install_github("rstudio/reticulate")
```
As a [workaround](https://github.com/rstudio/reticulate/pull/444#discussion_r416273920) this installs a working version:

```sh
git clone https://github.com/rstudio/reticulate.git
cd reticulate
```
```r
library("devtools")
document()
install()
```
