### ISSUE TITLE
Error installing leiden package in Rstudio

### ISSUE THREAD

**Issue by pangwopi** [TomKellyGenetics/leiden#6]
Hi Tom,

I was trying to install Leiden package in Rstudio, with no success. The error message is the following:

> install.packages("leiden")

  There is a binary version available but the source version is later:
       binary source needs_compilation
leiden  0.3.3  0.3.4             FALSE

installing the source package ‘leiden’

trying URL 'https://cran.rstudio.com/src/contrib/leiden_0.3.4.tar.gz'
Content type 'application/x-gzip' length 2002251 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

* installing *source* package ‘leiden’ ...
** package ‘leiden’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
sh: line 1:  2211 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/z5/7f3737q13dj2k63v65qb4mqr0000gn/T//RtmpBCo08G/file8904f8296ae'
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/leiden’
Warning in install.packages :
  installation of package ‘leiden’ had non-zero exit status

The downloaded source packages are in
‘/private/var/folders/z5/7f3737q13dj2k63v65qb4mqr0000gn/T/RtmpY7Ugmn/downloaded_packages’

My sessionInfo is below:

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    

loaded via a namespace (and not attached):
 [1] ps_1.4.0          fansi_0.4.1       prettyunits_1.1.1 rprojroot_1.3-2  
 [5] withr_2.3.0       digest_0.6.27     crayon_1.3.4      assertthat_0.2.1
 [9] R6_2.5.0          backports_1.1.10  magrittr_1.5      rlang_0.4.8      
[13] cli_2.1.0         fs_1.5.0          remotes_2.2.0     testthat_2.3.2  
[17] callr_3.5.1       ellipsis_0.3.1    desc_1.2.0        devtools_2.3.2  
[21] tools_4.0.2       glue_1.4.2        pkgload_1.1.0     compiler_4.0.2  
[25] processx_3.4.4    pkgbuild_1.1.0    sessioninfo_1.1.1 memoise_1.1.0    
[29] usethis_1.6.3    

Could you please help me troubleshooting? Any help is highly appreciated, thanks a lot!

**Comment by pangwopi** [comment]
Fixed the issue, it turns out that it is bacause I set Sys.getenv('R_MAX_VSIZE') for running another program. If I turn off that setting, the installation can be done without any problem. Still puzzling to me why this could happen. Anyways I will close this issue.

**Comment by TomKellyGenetics** [comment]
Thanks for reporting and updating with the solution in case others have similar issues. Glad you got it fixed. I'm confused by this as I've tested the packages on Mac OS 10.14 Mojave and Mac OS 10.15 Catalina.

Please note that I recommend running it in a conda environment. If you have not set one up already reticulate should install packages to the "r-reticulate" environment if conda is installed.

An upcoming release will have soft dependency on Python leidenalg with some functions available in R (or calling C directly).
